### PR TITLE
Added resources related to TF Extended

### PR DESCRIPTION
**Pull request by HackyRoot**

### CODE REVIEW

**Comment by manan-jadhav** [comment]
Can you please convert those notebooks to plain python scripts?

**Comment by HackyRoot** [comment]
I've no issue with that, but then I'll have to create Virtual environment also, in order to run the code properly on the local machine.

**Comment by manan-jadhav** [comment]
okay. can you add some notes as to how use those notebooks?

**Comment by HackyRoot** [comment]
I already added a tutorial link for that.

**Pull request merged**
